### ISSUE TITLE
42 Hour ToDo

### ISSUE THREAD

**Issue by samseaver** [ModelSEED/PlantSEED#13]
We fly Wednesday at 6:30pm.

**Feature Page**
Feature attributes:
-  ID
-   Function
-   Subsystem(s)
-  Aliases
- Protein Sequence

Plant Similarities:
-  ID    Genome    Function    Percent Identity

Prokaryotic Similarities:
-  ID    Genome    Function    Percent Identity

Plant Similarity ID(s) need to be linked back to original genome features, URL of which can be built using ID and Genome.

**Models**
-  List of public PlantSEED models.
-  Each PlantSEED model has a copy button for a user to copy to their workspace.
-  List of user plant models under "My Plant Models".

**Annotation**
-  Global Annotations page, I've one tiny request. Is it possible that when sorting the subsystems, the roles without a subsystem (i.e. with a "-" value) are sent to the bottom of the list?

-  Users Annotation page: 
  -  Place "Kmer Features" second, and re-name it to Features. Place "Blast Features" third and rename it "Exemplar Hits" (emphasis will be place on the Features first, Exemplars second).
  - Rename first column to "PlantSEED Role"
  - In any given role, can you highlight (perhaps by using bold or italics) features that are present in both second and third column

**Model Reconstruction**
Under "My Genomes" page, a genome has a "click to reconstruct" text that results in a pop-up. This needs to be a button that reconstructs directly with preset values for media and minimizefluxes.

**Comment by nconrad** [comment]
Hey @samseaver, for the feature page, if you don't already know, I don't see `genome` or 'function"prokaryotic_similarities

**Comment by nconrad** [comment]
Hey @samseaver, for the feature page, if you don't already know, I don't see `genome` or 'function` in the `prokaryotic_similarities` list.

**Comment by samseaver** [comment]
Fixed. The resulting view now shows plant and prokaryotic similarities correctly yay!
