### ISSUE TITLE
Timeline for PlantSEED 2016 Workshop at Northwestern

### ISSUE THREAD

**Issue by samseaver** [ModelSEED/PlantSEED#16]
Development environment:
    http://140.221.67.62/genomes/
    http://140.221.67.62/about/version

Workshop Dates:
    August 4th & 5th

Deadline for new main functionality (for alpha testing):
    July 1st

Deadline for improvements and fixes on all existing functionality (for beta testing):
    July 15th

Main functionality that needs to be added by July 1st (even if not yet mature):
    Account creation
    Genome upload/processing
    Plastidial Sandbox Genome/Model
    Transcriptomics FBA
    Visualization widget for comparing genomes

**Comment by samseaver** [comment]
Will post list of issues once development environment is fully working: http://140.221.67.62/genomes/

Not listing genomes etc. and feature pages are empty, investigating.

**Comment by nconrad** [comment]
I see in the console that this version of the site is pointing to http://p3c.theseed.org/dev1/services/ProbModelSEED, which is down...

**Comment by samseaver** [comment]
I re-started that service just now, I still get an exclamation mark in the version page, but it's now showing "My genomes". It's not showing "My models" or feature data however. We need to ensure that the appropriate portions of the development deployment *matches* what's in production, so to avoid any confusion.
